### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by kikito** [PartidoDeInternet/AgoraOnRails#14]
-- (comments)
pacoguzman4 Mar 2011, 7:31pm

Podríamos usar travis-ci https://github.com/travis-ci/travis-ci
Raimond Garcia5 Mar 2011, 8:58pm

Tiene buen pinta!

**Comment by afcapel** [comment]
It is now setup:

http://travis-ci.org/#!/PartidoDeInternet/AgoraOnRails/builds/244442
