### ISSUE TITLE
Registrar al usuario en el sistema a través del DNI electrónico

### ISSUE THREAD

**Issue by fbaile** [PartidoDeInternet/AgoraOnRails#16]
En el registro del usuario en el sistema se le pedirá que introduzca el DNIe. 
El sistema tendrá que obtener todos los datos disponibles del usuario que se encuentren en el formato del DNIe.
Además se pedirán los siguientes datos al usuario (opcionales):
- Email

**Comment by cavalle** [comment]
Duplicated
