### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by cavalle** [PartidoDeInternet/AgoraOnRails#17]
To include:
- A hacking guide: Explaining how to contribute (example in [cucumber's readme](https://github.com/aslakhellesoy/cucumber))
  1. Find or create an issue
  2. Add Comment to the issue to let people know you're going to work on it
  3. Fork
  4. Hack your changes in a [topic branch](https://github.com/dchelimsky/rspec/wiki/Topic-Branches)
  5. Pull request
  6. Wait for comments from maintainers or code merge
- Mention the IRC channel #agorarumble
- Any other change you find useful

Care about the copy. Use english. The README is one of the most important parts of an open source project ([RDD](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html))

**Comment by voodoorai2000** [comment]
On it!

**Comment by voodoorai2000** [comment]
Done
