### ISSUE TITLE
Spokesmen

### ISSUE THREAD

**Issue by cavalle** [PartidoDeInternet/AgoraOnRails#19]
In order to allow people to delegate its vote to me
As a commited citizen 
I want to become a spokesmen in the system

**Comment by cavalle** [comment]
Users should be able to upgrade to spokesman if they want to.

User cannot delegate to regular users, only to spokesmen

Spokesmen votes are always public, regular users votes are private (by default)

**Comment by rgo** [comment]
A-team (Rafa dixit) larioja-rb

**Comment by cavalle** [comment]
What's the status of this? Is it done?

**Comment by voodoorai2000** [comment]
We need to deal with the LOPD before making votes private.

Closing it for now.

**Comment by rgo** [comment]
We ended the first part (Users should be able to upgrade to spokesman).

I'll end this ticket an upload in a remote branch to have a prototype of this feature

**Comment by cavalle** [comment]
This issue wasn't about making votes private, but about not allowing everyone to be chosen as spokesman. We could just ignore the part of private votes.

Shouldn't we reopen it until rgo pushes his changes?
