### ISSUE TITLE
e-dni authenticated vote

### ISSUE THREAD

**Issue by kikito** [PartidoDeInternet/AgoraOnRails#2]
In order to have "real" votes
As a citizen
I want to authenticate myself with my DNI

**Comment by voodoorai2000** [comment]
Capel y yo cogemos este!

**Comment by cavalle** [comment]
Some work has already been pushed. One pending scenario right now.

**Comment by voodoorai2000** [comment]
scenario &#39;user registration using tractis&#39; closed by fd81985a4a09465c7369c228dc80d3f859d7d7f6
