### ISSUE TITLE
Spokesman selection does not prevent from selecting oneself

### ISSUE THREAD

**Issue by migbar** [PartidoDeInternet/AgoraOnRails#21]
How to re-create:
1 - While logged out, navigate to your own show page.
2 - Choose "Elegir a <yourself> como mi portavoz".
3 - Upon authentication, the redirect to the original request, makes it possible to elect yourself as your own spokesman.

The business rule is coded on the view. It might be moved to the model.

**Comment by emacip** [comment]
Migbar -emacip working

**Comment by cavalle** [comment]
Closed by 0790d97c51f33f8814199386eeb5200b989f1fb7
