### ISSUE TITLE
Cerrar las propuestas manualmente

### ISSUE THREAD

**Issue by fbaile** [PartidoDeInternet/AgoraOnRails#24]
El administrador / concejal / diputado podrá cerrar la propuesta manualmente.
Esto provocará que el sistema calcule los resultados de la votación y no permita a nadie seguir votando.

**Comment by jorgegorka** [comment]
Kilik85 y Jorgegorka comienzan el desarrollo

**Comment by jorgegorka** [comment]
Algunas cosas que conviene tener en cuenta:

Ahora un administrador puede cerrar cualquier propuesta.  
Debería poder comprobarse que solo quien ha creado una propuesta puede cerrarla?

Puede reabrirse una propuesta ya cerrada?

**Comment by voodoorai2000** [comment]
`Debería poder comprobarse que solo quien ha creado una propuesta puede cerrarla?`
De momento no.
Pero habrá que darle un vuelta al tema de permisos.

`Puede reabrirse una propuesta ya cerrada?`

No es necesario, pero podríamos usar [paper_trail](http://railscasts.com/episodes/255-undo-with-paper-trail) para estos temas de administración anti-cagadas.

Cierro el ticket con el commit [aa62463](https://github.com/PartidoDeInternet/AgoraOnRails/commit/aa6246308b43ea1e7964ceb83d5c5d7e0bb414a0)
