### ISSUE TITLE
Creating representatives

### ISSUE THREAD

**Issue by fbaile** [PartidoDeInternet/AgoraOnRails#26]
El administrador del sistema dará de alta los representantes de la circunscripción en la que estará instalado el sistema.
Un representante es la persona que lleva el resultado de la votación a la cámara de representación correspondiente.
El representante será el concejal, diputado, vocal, socio, etc ....
Cada sistema deberá tener una lista con todos los representantes del partido de internet.

Los datos que se pedirán para dar de alta al representante serán:
- Nombre 
- Apellidos
- Email
- DNI

**Comment by cavalle** [comment]
Work in progress? Is anyone working on this?

**Comment by voodoorai2000** [comment]
I miss-tagged this one.

Closing it in favor of [issue 37](https://github.com/PartidoDeInternet/AgoraOnRails/issues/37).
