### ISSUE TITLE
Repartir el resultado de la votación proporcionalmente entre los los representantes

### ISSUE THREAD

**Issue by fbaile** [PartidoDeInternet/AgoraOnRails#27]
Una vez concluida la votación, hay que repartir "proporcionalmente" el resultado de la votación entre los representantes del partido de internet dados de alta en el sistema.
Esto proporcionará la información necesaria a cada representante sobre qué tiene que votar.
El reparto se puede realizar de muchas maneras. Actualmente la función de representatividad que se usa es la Ley D'Hont. Sin embargo, existen otras muchas. Estos 2 documentos explican las funciones que existen y que se podrían aplicar:

http://partidodeinternet.es/wiki/Funcion_de_representacion#Explicaci.C3.B3n
http://partidodeinternet.es/wiki/Representatividad#Relaci.C3.B3n_entre_Rv_y_Rr

**Comment by cavalle** [comment]
Duplicated of #28
