### ISSUE TITLE
Spokesmen profile page

### ISSUE THREAD

**Issue by fbaile** [PartidoDeInternet/AgoraOnRails#30]
In order to get people to delegate their votes to me
As a spokesman 
I want to have a nice profile page including where I can put my resume, comments, images, links…

**Comment by hcarreras** [comment]
Working on it!
I think I will also implement that the profile page shows if that person is delegating to someone else, I think is really important.

**Comment by hcarreras** [comment]
I will have some delay, sorry! but I'm pretty busy right now!

**Comment by voodoorai2000** [comment]
No worries!

**Comment by hcarreras** [comment]
https://github.com/PartidoDeInternet/AgoraOnRails/pull/65

**Comment by hcarreras** [comment]
I think we can close this...

**Comment by voodoorai2000** [comment]
Sure!
