### ISSUE TITLE
Extract Spanish Congress scrapper from agora

### ISSUE THREAD

**Issue by cavalle** [PartidoDeInternet/AgoraOnRails#33]
The spanish congress scrapper might be useful for many other projects and, on the other side, there is only one use case of Agora where that data source will be used.

Apart from having a manual way of introducing data, it would be nice to create some kind of API in agora which would allow external modules (like the congress scrapper) to ingest and update proposals into the system

**Comment by afcapel** [comment]
https://rubygems.org/gems/congress-scrapper

Done!
