### ISSUE TITLE
Hi, any channel to talk?

### ISSUE THREAD

**Issue by hcarreras** [PartidoDeInternet/AgoraOnRails#57]
Hi there!
I'm Harí Carreras and I want to contribute with the project.
I would like to discuss about some topics, but I haven't seen any link to a group conversation, do you have one?
Also I was wondered why the webpage is offline. Any problem? Is the project still alive?
Meanwhile you answer me, I will try to see how can I support. 
=)

**Comment by voodoorai2000** [comment]
Hi Harí!

You are right, we need one! I just created it https://groups.google.com/forum/#!forum/agoraonrails
We can discuss anything there!

We are working on a redesign before putting the site up again.
But yes the project is alive and kicking ;)

Cheers,

Rai
