### ISSUE TITLE
Share your vote in Twitter

### ISSUE THREAD

**Issue by kikito** [PartidoDeInternet/AgoraOnRails#6]

**Comment by fbaile** [comment]
Tras realizarse la votación se da la opción al usuario de publicar en twitter que ha realizado la votación a través del partido de internet.
El mensaje sería algo parecido a:
"He votado a través del partido del internet la propuesta http://agoraonrails/proposals/XX"

**Comment by diasjorge** [comment]
Estamos trabajando en ello

**Comment by voodoorai2000** [comment]
Patch [6bfb87b](https://github.com/PartidoDeInternet/AgoraOnRails/commit/6bfb87b1ec5279fae35ebf85ec45969710c9eb8b) closes this ticket.
