### ISSUE TITLE
Mostrar el login en modo lightbox

### ISSUE THREAD

**Issue by kikito** [PartidoDeInternet/AgoraOnRails#9]
(bug)

Al intentar elegir a un representante sin estar logeado, sale el formulario en la esquina de arriba a la izquierda

**Comment by rgo** [comment]
Lo cogemos desde larioja-rb (A team)

**Comment by rgo** [comment]
Hemos añadido una vista(se muestra en el lightbox) confirmando que el usuario es el portavoz del usuario actual. Tiene el mismo comportamiento que los votos.

**Comment by rgo** [comment]
Creemos que estaría bien sacar el login/registro del popup y ponerlo en una pantalla separada. No se, darle una pensada.

**Comment by voodoorai2000** [comment]
Closed with commit [6efd8c3](https://github.com/PartidoDeInternet/AgoraOnRails/commit/6efd8c321c45ade1f0ec6e09a587bfc61d34f5b4)
